### ISSUE TITLE
Invalid ZoneOffset when syncing in Persian language

### ISSUE THREAD

**Issue by MohammadFakhraee** [bitfireAT/ical4android#75]
When setting phone language to "fa" (Which is for Iran language), DAVx5 shows notification with `Invalid ID for ZoneOffset, non numeric characters found: +۰۳۲۵۴۴` message every time I press sync button.

Steps to reproduce:
1. set davx5 language to Persian (فارسی) with/or "fa" locale.
2. Add an event with Etar calendar application. (it might be produced with other applications, but I tested this app so far). Make sure the event is not an **AllDay** event, otherwise the bug won't produce.
3. Come back to DAVx5 application and hit sync button.

This is the bug I get:
```
j$.time.d: Invalid ID for ZoneOffset, non numeric characters found: +۰۳۲۵۴۴
	at j$.time.ZoneOffset.R(Unknown Source:83)
	at j$.time.ZoneOffset.of(Unknown Source:75)
	at net.fortuna.ical4j.model.property.TzOffsetFrom.setValue(TzOffsetFrom.java:3)
	at net.fortuna.ical4j.model.property.TzOffsetFrom.<init>(TzOffsetFrom.java:5)
	at net.fortuna.ical4j.model.property.TzOffsetFrom$Factory.createProperty(TzOffsetFrom.java:3)
	at net.fortuna.ical4j.model.property.TzOffsetFrom$Factory.createProperty(TzOffsetFrom.java:2)
	at net.fortuna.ical4j.model.Property.copy(Property.java:21)
	at net.fortuna.ical4j.model.PropertyList.<init>(PropertyList.java:5)
	at net.fortuna.ical4j.model.Component.copy(Component.java:5)
	at net.fortuna.ical4j.model.ComponentList.<init>(ComponentList.java:5)
	at net.fortuna.ical4j.model.Component.copy(Component.java:12)
	at at.bitfire.ical4android.ICalendar$Companion.minifyVTimeZone(ICalendar.kt:6)
	at at.bitfire.ical4android.Event.write(Event.kt:439)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$generateUpload$1.invoke(CalendarSyncManager.kt:7)
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager$generateUpload$1.invoke(CalendarSyncManager.kt:1)
```

Here is also the debug report:
 
[davx5-debug.zip](https://github.com/bitfireAT/ical4android/files/10436209/davx5-debug.zip)

**Comment by ArnyminerZ** [comment]
I can't manage to reproduce. Steps followed:
1. Add a remote collection to DAVx⁵.
2. Set phone language to Persian.
3. Create an event with the default parameters from Etar.
4. Synchronize from DAVx⁵.

Please, can you give more details on how to reproduce? Also, please, report from [davx5-ose](https://github.com/bitfireAT/davx5-ose) when it's related to DAVx⁵.
